### ISSUE TITLE
Feat : 문장 완성 기능 / 주제 추천 기능 통합하는 프롬프트 개발

### ISSUE THREAD

**Issue by J-nowcow** [Review-Mate/Review-Mate-AI-GPT#17]
### 문제 상황
- 어떤 상황에서 문장 완성을 해야 할지, 주제 추천을 해야 할지 알 수 없음
- 마지막 문장이 완성되었는지를 기준으로 판단하는데, 이 판단 또한 gpt한테 시킬 수 있을 것으로 판단됨
- 마지막 문장의 완성 여부 판단 + 기존 프롬프트 로 gpt를 두번 호출하는 코드를 작성하면 전체 호출 시간이 느려질 것으로 판단됨 -> 통합된 하나의 프롬프트로 작성

**Comment by J-nowcow** [comment]
### TODO
---
- [x] 통합 프롬프트 작성 및 테스트
- [x] 프론트에서 원하는 양식에 맞춰 gpt 출력값 후처리
- [x] AWS api 연결
- [x] 기존 코드 삭제
